locale = {
	'EN' : {
		'gem'            : 'Gem',
		'prongs'         : 'Prongs',
		'cutter'         : 'Cutter',
		'imitation'      : 'Imitation',
		'make_gem'       : 'Make Gem',
		'make_dupliface' : 'Make Dupli-face',
		'select_doubles' : 'Select Doubles',
		'export_options' : 'Export Options',
		'metals'         : 'Metals',
		'export_stats'   : 'Export Stats',
		'locale'         : 'Localization',
		'lang'           : 'Language',
		'size'           : 'Size',
		'shank'          : 'Shank',
		'dim'            : 'Dimensions',
		'weight'         : 'Weight',
		'cut'            : 'Cut',
		'qty'            : 'Qty',

		'round'     : 'Round',
		'oval'      : 'Oval',
		'pear'      : 'Pear',
		'marquise'  : 'Marquise',
		'baguette'  : 'Baguette',
		'square'    : 'Square',
		'cushion'   : 'Cushion',
		'asscher'   : 'Asscher',
		'princess'  : 'Princess',
		'trillion'  : 'Trillion',
		'octagon'   : 'Octagon',
		'heart'     : 'Heart',
		'radiant'   : 'Radiant',
		'flanders'  : 'Flanders',
		'trilliant' : 'Trilliant',
		'triangle'  : 'Triangle',

		'diamond'        : 'Diamond',
		'amethyst'       : 'Amethyst',
		'aquamarine'     : 'Aquamarine',
		'citrine'        : 'Citrine',
		'cubic_zirconia' : 'Cubic Zirconia',
		'emerald'        : 'Emerald',
		'garnet'         : 'Garnet',
		'morganite'      : 'Morganite',
		'peridot'        : 'Peridot',
		'quartz'         : 'Quartz',
		'ruby'           : 'Ruby',
		'sapphire'       : 'Sapphire',
		'spinel'         : 'Spinel',
		'tanzanite'      : 'Tanzanite',
		'topaz'          : 'Topaz',
		'tourmaline'     : 'Tourmaline',
		'zircon'         : 'Zircon',

		'24g'  : '24 kt. Gold',
		'22g'  : '22 kt. Gold',
		'18wg' : '18 kt. White gold',
		'14wg' : '14 kt. White gold',
		'18yg' : '18 kt. Yellow gold',
		'14yg' : '14 kt. Yellow gold',
		'ster' : 'Sterling Silver',
		'pd'   : 'Palladium',
		'pl'   : 'Platinum',

		'custom'      : 'Custom density:',
		'custom_name' : 'Material:',

		'wt_vol'    : 'Volume (mm³)',
		'wt_custom' : 'Custom density (g/cm³)',
		'wt_calc'   : 'Calculate',

		'items' : 'items',
		'mm'    : 'mm',
		'mm3'   : 'mm³',
		'g'     : 'g',
		'ct'    : 'ct.',
		'g/cm'  : 'g/cm³',

		'f_size'      : 'Size:',
		'f_shank'     : 'Shank:',
		'f_dim'       : 'Dimensions:',
		'f_weight'    : 'Weight:',
		'f_settings'  : 'Settings:',

		'report_doubles'    : 'Found %d dplicates',
		'report_no_doubles' : 'No duplicates found',
		'report_stats'      : 'stats.txt successfully created in the project folder',

		'error_file' : 'First save your blend file',
	},
	'RU' : {
		'gem'            : 'Камень',
		'prongs'         : 'Крапана',
		'cutter'         : 'Выборка',
		'imitation'      : 'Имитация',
		'make_gem'       : 'Создать Камень',
		'make_dupliface' : 'Создать Dupli-face',
		'select_doubles' : 'Выделить Дубликаты',
		'export_options' : 'Опции Экспорта',
		'metals'         : 'Металлы',
		'export_stats'   : 'Экспорт Статистики',
		'locale'         : 'Локализация',
		'lang'           : 'Язык',
		'size'           : 'Размер',
		'shank'          : 'Шинка',
		'dim'            : 'Габариты',
		'weight'         : 'Вес',
		'cut'            : 'Огранка',
		'qty'            : 'Количество',

		'round'     : 'Кр-57',
		'oval'      : 'Овал',
		'pear'      : 'Груша',
		'marquise'  : 'Маркиз',
		'baguette'  : 'Багет',
		'square'    : 'Квадрат',
		'cushion'   : 'Кушон',
		'asscher'   : 'Ашер',
		'princess'  : 'Принцесса',
		'trillion'  : 'Триллион',
		'octagon'   : 'Октагон',
		'heart'     : 'Сердце',
		'radiant'   : 'Радиант',
		'flanders'  : 'Фландерс',
		'trilliant' : 'Триллиант',
		'triangle'  : 'Треугольник',

		'diamond'        : 'Бриллиант',
		'amethyst'       : 'Аметист',
		'aquamarine'     : 'Аквамарин',
		'citrine'        : 'Цитрин',
		'cubic_zirconia' : 'Фианит',
		'emerald'        : 'Изумруд',
		'garnet'         : 'Гранат',
		'morganite'      : 'Морганит',
		'peridot'        : 'Хризолит',
		'quartz'         : 'Кварц',
		'ruby'           : 'Рубин',
		'sapphire'       : 'Сапфир',
		'spinel'         : 'Шпинель',
		'tanzanite'      : 'Танзанит',
		'topaz'          : 'Топаз',
		'tourmaline'     : 'Турмалин',
		'zircon'         : 'Циркон',

		'24g'  : '999 Золото',
		'22g'  : '916 Золото',
		'18wg' : '750 Белое золото',
		'14wg' : '585 Белое золото',
		'18yg' : '750 Жёлтое золото',
		'14yg' : '585 Жёлтое золото',
		'ster' : 'Стерлинг серебро',
		'pd'   : 'Палладий',
		'pl'   : 'Платина',

		'custom'      : 'Произвольная плотность:',
		'custom_name' : 'Материал:',

		'wt_vol'    : 'Объем (мм³)',
		'wt_custom' : 'Произвольная плотность (г/см³)',
		'wt_calc'   : 'Вычислить',

		'items' : 'шт.',
		'mm'    : 'мм',
		'mm3'   : 'мм³',
		'g'     : 'г',
		'ct'    : 'кар',
		'g/cm'  : 'г/см³',

		'f_size'      : 'Размер:',
		'f_shank'     : 'Шинка:',
		'f_dim'       : 'Габариты:',
		'f_weight'    : 'Вес:',
		'f_settings'  : 'Вставки:',

		'report_doubles'    : 'Обнаружено %d дубликатов',
		'report_no_doubles' : 'Дубликаты не обнаружены',
		'report_stats'      : 'stats.txt успешно создан в каталоге проекта',

		'error_file' : 'Сначала сохраните ваш blend файл',
	}
}
