locale = {
	'EN' : {
		'gem'            : 'Gem',
		'prongs'         : 'Prongs',
		'cutter'         : 'Cutter',
		'imitation'      : 'Imitation',
		'make_gem'       : 'Make Gem',
		'make_dupliface' : 'Make Dupli-face',
		'select_dupli'   : 'Select Duplicates',
		'export_options' : 'Export Options',
		'metals'         : 'Metals',
		'export_stats'   : 'Export Stats',
		'locale'         : 'Localization',
		'lang'           : 'Language',

		'size'   : 'Size',
		'shank'  : 'Shank',
		'dim'    : 'Dimensions',
		'weight' : 'Weight',

		'type' : 'Type',
		'cut'  : 'Cut',
		'qty'  : 'Qty',

		'items' : 'items',
		'mm'    : 'mm',
		'mm3'   : 'mm³',
		'g'     : 'g',
		'ct'    : 'ct.',
		'g/cm'  : 'g/cm³',

		'24kt'        : '24 kt. Gold',
		'22kt'        : '22 kt. Gold',
		'18kt_white'  : '18 kt. White gold',
		'14kt_white'  : '14 kt. White gold',
		'18kt_yellow' : '18 kt. Yellow gold',
		'14kt_yellow' : '14 kt. Yellow gold',
		'sterling'    : 'Sterling Silver',
		'palladium'   : 'Palladium',
		'platinum'    : 'Platinum',
		'custom'      : 'Custom density:',
		'custom_name' : 'Material:',

		'wt_vol'    : 'Volume (mm³)',
		'wt_custom' : 'Custom density (g/cm³)',
		'wt_calc'   : 'Calculate',

		'diamond'        : 'Diamond',
		'amethyst'       : 'Amethyst',
		'aquamarine'     : 'Aquamarine',
		'citrine'        : 'Citrine',
		'cubic_zirconia' : 'Cubic Zirconia',
		'emerald'        : 'Emerald',
		'garnet'         : 'Garnet',
		'quartz'         : 'Quartz',
		'peridot'        : 'Peridot',
		'ruby'           : 'Ruby',
		'sapphire'       : 'Sapphire',
		'spinel'         : 'Spinel',
		'tanzanite'      : 'Tanzanite',
		'topaz'          : 'Topaz',
		'tourmaline'     : 'Tourmaline',

		'round'     : 'Round',
		'oval'      : 'Oval',
		'pear'      : 'Pear',
		'marquise'  : 'Marquise',
		'baguette'  : 'Baguette',
		'square'    : 'Square',
		'cushion'   : 'Cushion',
		'asscher'   : 'Asscher',
		'princess'  : 'Princess',
		'trillion'  : 'Trillion',
		'octagon'   : 'Octagon',
		'heart'     : 'Heart',
		'radiant'   : 'Radiant',
		'flanders'  : 'Flanders',
		'trilliant' : 'Trilliant',

		'report_dupli'    : 'Duplicated gems found',
		'report_no_dupli' : 'No duplicates found',

		'error_file' : 'First save your blend file',

		# Statsistics template locale
		't_size'      : 'Size:',
		't_width'     : 'Width:',
		't_thickness' : 'Thickness:',
		't_dim'       : 'Dimensions:',
		't_weight'    : 'Weight:',
		't_settings'  : 'Settings:',
	},
	'RU' : {
		'gem'            : 'Камень',
		'prongs'         : 'Крапана',
		'cutter'         : 'Выборка',
		'imitation'      : 'Имитация',
		'make_gem'       : 'Создать Камень',
		'make_dupliface' : 'Создать Dupli-face',
		'select_dupli'   : 'Выделить Дубликаты',
		'export_options' : 'Опции Экспорта',
		'metals'         : 'Металлы',
		'export_stats'   : 'Экспорт Статистики',
		'locale'         : 'Локализация',
		'lang'           : 'Язык',

		'size'   : 'Размер',
		'shank'  : 'Шинка',
		'dim'    : 'Габариты',
		'weight' : 'Вес',

		'type' : 'Тип',
		'cut'  : 'Огранка',
		'qty'  : 'Количество',

		'items' : 'шт.',
		'mm'    : 'мм',
		'mm3'   : 'мм³',
		'g'     : 'г',
		'ct'    : 'кар',
		'g/cm'  : 'г/см³',

		'24kt'        : '999 Золото',
		'22kt'        : '916 Золото',
		'18kt_white'  : '750 Белое золото',
		'14kt_white'  : '585 Белое золото',
		'18kt_yellow' : '750 Жёлтое золото',
		'14kt_yellow' : '585 Жёлтое золото',
		'sterling'    : 'Стерлинг серебро',
		'palladium'   : 'Палладий',
		'platinum'    : 'Платина',
		'custom'      : 'Произвольная плотность:',
		'custom_name' : 'Материал:',

		'wt_vol'    : 'Объем (мм³)',
		'wt_custom' : 'Произвольная плотность (г/см³)',
		'wt_calc'   : 'Вычислить',

		'diamond'        : 'Бриллиант',
		'amethyst'       : 'Аметист',
		'aquamarine'     : 'Аквамарин',
		'citrine'        : 'Цитрин',
		'cubic_zirconia' : 'Фианит',
		'emerald'        : 'Изумруд',
		'garnet'         : 'Гранат',
		'quartz'         : 'Кварц',
		'peridot'        : 'Хризолит',
		'ruby'           : 'Рубин',
		'sapphire'       : 'Сапфир',
		'spinel'         : 'Шпинель',
		'tanzanite'      : 'Танзанит',
		'topaz'          : 'Топаз',
		'tourmaline'     : 'Турмалин',

		'round'     : 'Кр-57',
		'oval'      : 'Овал',
		'pear'      : 'Груша',
		'marquise'  : 'Маркиз',
		'baguette'  : 'Багет',
		'square'    : 'Квадрат',
		'cushion'   : 'Кушон',
		'asscher'   : 'Ашер',
		'princess'  : 'Принцесса',
		'trillion'  : 'Триллион',
		'octagon'   : 'Октагон',
		'heart'     : 'Сердце',
		'radiant'   : 'Радиант',
		'flanders'  : 'Фландерс',
		'trilliant' : 'Триллиант',

		'report_dupli'    : 'Обнаружены дублированные камни',
		'report_no_dupli' : 'Дубликаты не обнаружены',

		'error_file' : 'Сначала сохраните ваш blend файл',

		# Локализация шаблона статистики
		't_size'      : 'Размер:',
		't_width'     : 'Ширина:',
		't_thickness' : 'Толщина:',
		't_dim'       : 'Габариты:',
		't_weight'    : 'Вес:',
		't_settings'  : 'Вставки:',
	}
}
