# ##### BEGIN GPL LICENSE BLOCK #####
#
#  JewelCraft jewelry design toolkit for Blender.
#  Copyright (C) 2015-2019  Mikhail Rachinskiy
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# ##### END GPL LICENSE BLOCK #####


dictionary = {
    "*": {
        "Asset Manager": "Navigateur de ressources",
        "Display Asset Name": "Affiche le nom de la Ressource",
        "Product Report": "Rapport de produit",
        "Report Language": "Langue du rapport",
        "Save To File": "Enregistre vers un fichier",
        "Use Custom Library Folder": "Utiliser un dossier de librairie personnalisé",
        "Gems": "Pierres précieuses",
        "Assets": "Ressources",
        "Select Gems By...": "Sélectionner les pierres par...",
        "Jeweling": "Bijouterie",
        "Weighting": "Poids",
        "Weighting Set": "Catégories de poids",
        "Hide Default Sets": "Cacher les catégories par défaut",
        "[JewelCraft] Precious": "[JewelCraft] Précieux",
        "[JewelCraft] Precious RU (ГОСТ 30649-99)": "[JewelCraft] Précieux RU (ГОСТ 30649-99)",
        # "[JewelCraft] Base": "",
        "Prongs": "Grains",
        "Cutter": "Alésage",
        "Library Folder Path": "Chemin du dossier de librairie",
        # "Widgets": "",
        "Use Overrides": "Utiliser les substitutions",
        "Widget Color": "Couleur du widget",
        "Line Width": "Epaisseur de ligne",
        "Show Composition": "Afficher la composition",
        "Show Density": "Afficher la densité",
        # "Composition": "",
        "Warnings": "Avertissements",
        "Hidden Gems": "Cacher les pierres",
        "Show All": "Tout montrer",
        "Scene scale is not optimal": "L'échelle de la scène n'est pas optimal",
        "Unsupported unit system": "Système d'unités non supporté",
        "Overlapping Gems": "Superposition de pierres",
        "Limit By Selection": "Limiter à la sélection",
        "Save To Image": "Enregistrer au format image",
        "Gem Map": "Plan d'empierrage",
        "Gem Table": "Tableau des pierres",
        "Gem Size": "Dimension des pierres",
        "Viewport Text Size": "Taille du texte",
        "Weight": "Poids",
        "Asset Name": "Nom de la ressources",
        "Category Name": "Nom des catégories",
        "Set Name": "Nommer",
        "Curvature Scale": "Echelle de la courbe",
        "Prong Number": "Nombre de grains",
        "Detalization": "Niveau de détail",
        # "Intersection": "",
        "Bump Scale": "Niveau de boulé",
        "Diameter": "Diamètre",
        "Size Offset": "Décalage de taille",
        "Girdle": "Feuilletis",
        "Hole": "Percage",
        "Culet": "Cullase",
        "Handle": "Poignée",
        "Curve Seat": "Siège de la courbe",
        "Curve Profile": "Profil de la courbe",
        "Bevel Corners": "Coins biseautés",
        "Length Offset": "Décalage de longueur",
        "Width Offset": "Décalage de largueur",
        "Position Offset": "Décalage de la position",
        "Start Up": "Démarrage",
        "Mirror Axis": "Axe de symétrie",
        "Select Children": "Sélectionner l'enfant",
        "Parent to selected": "Parent de la sélection",
        "Use 3D Cursor": "Utiliser le curseur 3D",
        "Collection Name": "Nom de la collection",
        "Ring Size": "Taille de doigt",
        # "USA": "",
        "Britain": "Grande Bretagne",
        "Swiss": "Suisse",
        "Japan": "Japon",
        "Circumference": "Périmètre",
        "Scatter (%)": "Distribution (%)",
        # "Only ID": "",
        # "Force Edit": "",
        "Add gemstone to the scene": "Ajouter une pierre précieuse à la scène",
        "Edit selected gems": "Editer les pierres sélectionnées",
        # "Force edit selected mesh objects, can be used to make gems from non-gem objects": "",
        # "Only edit gem identifiers, not affecting object data and materials": "",
        "Commonly used precious alloys, physical properties taken directly from suppliers": "Alliages précieux couramment utilisés, propriétés physiques récupérées directement auprès des fournisseurs",
        "Set of precious alloys according to Russian regulations": "Ensemble d'alliages précieux selon la réglementation russe",
        "Set of base metal alloys, physical properties taken directly from suppliers": "Ensemble d'alliages de métaux communs, propriétés physiques récupérées directement auprès des fournisseurs",
        "Save product report to file in project folder": "Enregistrer le rapport du produit dans un fichier dans le dossier du projet",
        "Product report language": "Langue du rapport du produit",
        "Use user preferences language setting": "Utiliser les paramètres de langue des préférences utilisateur",
        "Select gems by trait": "Sélectionnez des pierres par trait",
        "Search stone by name": "Chercher les pierres par nom",
        "Search asset by name": "Chercher les ressources par nom",
        "Scatter selected object along active curve": "Distribuer l'objet sélectionné le long de la courbe active",
        "Redistribute selected objects along curve": "Redistribuer les objets sélectionnés le long de la courbe",
        "Display weight and volume for selected mesh objects": "Afficher le poids et le volume pour les maillages sélectionnés",
        "Create instance face for selected objects": "Créer une instance de face pour les objets sélectionnés",
        "Create size curve": "Créer une courbe de taille",
        "Stretch deformed objects along curve on X axis, also works in Edit Mode with selected vertices": "Étirer les objets déformés le long de la courbe sur l’axe X, fonctionne également en mode édition avec les sommets sélectionnés",
        "Display curve length": "Afficher la longueur de la courbe",
        "Move deformed object over or under the curve": "Déplacer l'objet déformé au dessus ou au dessous de la courbe",
        "Mirror selected objects around one or more axes, keeping object data linked": "Symétriser les objets sélectionnés autour d'un ou plusieurs axes, en maintenant les données d'objets liées",
        "Project selected objects onto active object using Lattice": "Projeter des objets sélectionnés sur un objet actif à l'aide de Lattice",
        "Deform active object profile with Lattice": "Déformer le profil d'objet actif avec Lattice",
        "Create prongs for selected gems\n(Shortcut: hold Ctrl when using the tool to avoid properties reset)": "Créer des grains pour les pierres sélectionnées\n(Shortcut: maintenez la touche Ctrl pour éviter la remise à zéro des paramètres)",
        "Create cutter for selected gems\n(Shortcut: hold Ctrl when using the tool to avoid properties reset)": "Créer une coupe pour les pierres sélectionnées\n(Shortcut: maintenez la touche Ctrl pour éviter la remise à zéro des paramètres)",
        "Make curve start at the top": "Faire que la courbe commence en haut",
        "Density g/cm³": "Densité g/cm³",
        "Set of materials for weighting": "Ensemble de matériaux pour le calcul du poid",
        "Create category": "Créer une catégorie",
        "Rename category": "Renommer une catégorie",
        "Refresh asset UI": "Rafraichir le menu des ressources",
        "Add selected objects to asset library": "Ajouter les objets sélectionnés à la bibliothèque de ressources",
        "Rename asset": "Renommer la ressource",
        "Remove asset from library": "Retirer la ressource de la librairie",
        "Replace current asset with selected objects": "Remplacer la ressource actuelle avec les objets sélectionnés",
        "Replace asset preview image": "Remplacer la vignette de la ressource",
        "Import selected asset": "Importer la ressource sélectionnée",
        "Asset category": "Catégorie de la ressource",
        "Set custom asset library folder, if disabled the default library folder will be used": "Définir le dossier de la bibliothèque de ressources personnalisée; le cas échéant, le dossier de la bibliothèque par défaut sera utilisé",
        "Custom library folder path": "Chemin du dossier de la bibliothèque personnalisée",
        "Display asset name in Tool Shelf": "Afficher le nom de la ressource dans Tool Shelf",
        "Enable widgets drawing": "Activer le dessin des widgets",
        "Use object defined widget overrides": "Utiliser les substitutions de widget définis pour l'objet",
        "Draw widgets in front of objects": "Dessiner des widgets devant des objets",
        "Override widget display properties for selected objects": "Substituer les propriétés d'affichage du widget pour les objets sélectionnés",
        "Remove widget override properties from selected objects": "Supprimer les propriétés de substitution de widget des objets sélectionnés",
        "Add new material to the list": "Ajouter un nouveau matériau à la liste",
        "Display material density in the list": "Afficher la densité du matériau dans la liste",
        "Display material composition in the list": "Afficher la composition du matériau dans la liste",
        "Create weighting set from materials list": "Créer une catégorie de poids à partir de la liste des matériaux",
        "Remove weighting set": "Retirer la catégorie de poids",
        "Rename weighting set": "Renommer la catégorie de poids",
        "Load weighting set to the materials list by replacing existing materials": "Charger la catégorie de poids dans la liste des matériaux en remplaçant les matériaux existants",
        "Append weighting set at the end of the current materials list": "Ajouter la catégorie de poids à la fin de la liste des matières en cours",
        "Hide default JewelCraft sets from weighting sets menu": "Masquer les catégories par défaut de JewelCraft dans le menu des catégories de poids",
        "Replace selected weighting set with current materials list": "Remplacer la catégorie de poids sélectionnée par la liste des matériaux en cours",
        "Material name": "Nom du matériau",
        "Material composition": "Composition du matériau",
        "Use one-dimensional lattice for even deformation": "Utilisez un treillis unidimensionnel pour une déformation uniforme",
        "Use two-dimensional lattice for proportional deformation": "Utiliser un treillis bidimensionnel pour une déformation proportionnelle",
        "Scale selected objects to given size": "Mettre à l'échelle les objets sélectionnés à une taille donnée",
        "Move each object individually": "Déplacer chaque objet individuellement",
        "Enable material for weighting and product report": "Activer le matériau pour le calcul du poids et le rapport de produit",
        "Parent imported asset to selected objects (Shortcut: hold Alt when using the tool)": "Aparenter la ressource importée pour les objets sélectionnés (Raccourci: presser la touche Alt en utilisant l'outil)",
        "Select gems that are less than 0.1 mm distance from each other or overlapping": "Sélectionner les pierres qui ont moins de 0,1mm de distance entre elles ou qui se superposent",
        "Display spacing widget for all visible gems": "Afficher les zones d'espacement pour toutes les pierres visibles",
        "Set optimal unit settings for jewelry modelling": "Définir les unités optimales pour la modélisation en Joaillerie",
        "Enable or disable given warning": "Activer ou désactiver les avertissements donnés",
        "Compose gem table and map it to gems in the scene": "Composer un tableau de pierres et l'appliquer sur les pierres dans la scène",
        "Present summary information about the product, including gems, sizes and weight": "Présenter le résumé des informations à propos du projet, incluant les pierres, dimensions et poids",
        "Add a new measurement": "Ajouter une nouvelle mesure",
        "Remove selected item": "Retirer l'objet sélectionné",
        "Remove all list items": "Retirer tous les objets dans la liste",
        "Move selected item up/down in the list": "Déplacer les objets sélectionnés dans la liste vers le haut ou vers le bas",
        "Measured object": "Objet mesuré",
        "Measurement type": "Type de mesure",
        "Select material": "Sélectionner la matière",
        "Make collection instances in radial order\n(Shortcut: hold Alt when using the tool to use existing collection)": "Trier les intance de la collection dans l'ordre radial\n (Raccourci: presser la touche Atl en utilisant cet outil pour utiliser une collection existante)",
        "Include or exclude given column": "Inclure ou exclure la colonne donnée",
        "Autoload marked weighting set on File > Open/New if materials list for given blend file is empty": "Charger automatiquemenent la catégorie de poids définie dans Fichier > Ouvrir/Nouveau si la liste de matériaux pour le fichier de fusion donné est vide",
        "WARNING": "AVERTISSEMENT",
        "Possible gem instance face leftovers": "Restes d'instance de face de pierres possibles",
        "Hidden gems": "Pierres cachées",
        "Deprecated gem IDs (use Convert Deprecated Gem IDs from Operator Search menu)": "ID de pierre obsolète (utiliser Convertir les IDs de pierres Obsolètes dans le menu de recherche de fonction)",
        "Unknown gem IDs, carats are not calculated for marked gems (*)": "IDs de pierre inconnus, les carats ne sont pas calculés pour des pierres marquées (*)",
        "Curve Length": "Longueur de la courbe",
        "Missing selected objects": "Pas d'objets sélectionnés",
        "At least two objects must be selected": "Au moins deux objets doivent être sélectionnés",
        "At least one gem object must be selected": "Au moins une pierre doit être sélectionnée",
        "At least one mesh object must be selected": "Au moins un maillage doit être sélectionné",
        "Active object must be a curve": "L'objet actif doit être une courbe",
        "Selected objects do not have Follow Path constraint": "Les objets sélectionnés n'ont pas de contrainte de suivi de chemin",
        "File not found": "Fichier non trouvé",
        "Name must be specified": "Le nom doit être spécifié",
        "Collection must be specified": "La Collection doit être spécifiée",
        "Overlapping gems": "Pierres en superposition",
        "{} overlaps found": "{} superpositions trouvées",
        "Optimal unit settings are in use": "Les unités optimales sont définies",
        # "Volume": "",
        "Settings": "Réglages",
        "Gem": "Pierre",
        "Cut": "Taille",
        "Qty": "Qté",
        # "Total (ct.)": "",
        # "Carats": "",
        "Materials": "Matière",
        "Additional Notes": "Notes additionelles",
        "Round": "Rond",
        "Oval": "Ovale",
        "Cushion": "Coussin",
        "Pear": "Poire",
        # "Marquise": "",
        "Princess": "Princesse",
        # "Baguette": "",
        "Square": "Carré",
        # "Asscher": "",
        # "Radiant": "",
        # "Flanders": "",
        "Octagon": "Octaèdre",
        "Heart": "Coeur",
        "Trillion": "Billion",
        # "Trilliant": "",
        # "Triangle": "",
        # "Alexandrite": "",
        "Amethyst": "Amethyste",
        "Aquamarine": "Aigue-Marine",
        # "Citrine": "",
        "Cubic Zirconia": "Zircon cubique",
        "Diamond": "Diamant",
        "Emerald": "Emeraude",
        "Garnet": "Grenat",
        # "Morganite": "",
        "Peridot": "Péridot",
        # "Quartz": "",
        "Ruby": "Rubis",
        "Sapphire": "Saphir",
        "Spinel": "Spinelle",
        # "Tanzanite": "",
        "Topaz": "Topaze",
        # "Tourmaline": "",
        # "Zircon": "",
        "Yellow Gold 24K": "Or Jaune 24K",
        "Yellow Gold 22K": "Or Jaune 22K",
        "Yellow Gold 18K": "Or Jaune 18K",
        "Yellow Gold 14K": "Or Jaune 14K",
        "Yellow Gold 10K": "Or Jaune 10K",
        "White Gold 18K Pd": "Or Blanc 18K Pd",
        "White Gold 18K Ni": "Or Blanc 18K Ni",
        "White Gold 14K Pd": "Or Blanc 14K Pd",
        "White Gold 14K Ni": "Or Blanc 14K Ni",
        "White Gold 10K": "Or Blanc 10K",
        "Rose Gold 18K": "Or Rose 18K",
        "Rose Gold 14K": "Or Rose 14K",
        "Rose Gold 10K": "Or Rose 10K",
        "Yellow Gold 999": "Or Jaune 999",
        "Yellow Gold 958": "Or Jaune 958",
        "Yellow Gold 750": "Or Jaune 750",
        "Yellow Gold 585": "Or Jaune 585",
        "Yellow Gold 375": "Or Jaune 375",
        "White Gold 750 Pd": "Or Blanc 750 Pd",
        "White Gold 750 Ni": "Or Blanc 750 Ni",
        "White Gold 585 Pd": "Or Blanc 585 Pd",
        "White Gold 585 Ni": "Or Blanc 585 Ni",
        "Red Gold 585": "Or Rouge 585",
        "Red Gold 375": "Or Rouge 375",
        "Platinum 950": "Platine 950",
        "Platinum 900": "Platine 900",
        # "Palladium 950": "",
        "Silver 925": "Argent 925",
        "Silver Sterling": "Argent Sterling",
        "Brass": "Laiton",
        # "Bronze": "",
        "Steel Stainless": "Acier Inoxydable",
        "Titanium": "Titane",
        # "mm": "",
        # "mm³": "",
        # "g": "",
        # "ct.": "",
        # "pcs": "",
    },
    "JewelCraft": {
        "Cut": "Taille",
        "Round": "Rond",
        "Spacing": "Espace",
    },
    "Dative": {
        "Size": "Dimension",
        "Stone": "Pierre",
        "Cut": "Taille",
    },
    "Operator": {
        "Add Gem": "Ajouter une pierre",
        "Curve Scatter": "Distribution de la courbe",
        "Prongs": "Grains",
        "Cutter": "Alésage",
        "Make Instance Face": "Créer une instance face",
        "Lattice Project": "Projection de treillis",
        "Lattice Profile": "Profil du treillis",
        "Size Curve": "Dimension de la courbe ",
        "Stretch": "Étirer",
        "Curve Length": "Longueur de la courbe",
        "Product Report": "Rapport du produit",
        "Open Library Folder": "Ouvrir le dossier de la librairie",
        "Import Asset": "Importer la ressource",
        "Rename": "Renommer",
        "Replace Asset": "Remplacer la ressource",
        "Replace Preview": "Remplacer la prévisualisation",
        "Create Category": "Créer une catégorie",
        "Rename Category": "Créer une catégorie",
        "Rename Asset": "Renommer la ressource",
        "Remove Asset": "Remplacer la ressource",
        "Replace Asset Preview": "Remplacer la prévisualisation de la ressource",
        "Override": "Substituer",
        "Clear List": "Effacer la liste",
        "Add New Material": "Ajouter un nouveau matériau",
        "Create Set": "Créer un ensemble",
        "Replace Set": "Remplacer un ensemble",
        "Remove Set": "Effacer un ensemble",
        "Rename Set": "Renommer un ensemble",
        "Overlapping": "Superposition",
        "Set Units": "Définir les unités",
        "Gem Map": "Plan d'empierrage",
        "Append": "Ajouter",
        "Add New Measurement": "Ajouter une nouvelle mesure",
        "Mark Autoload": "Chargement automatique",
    },
}
