# ##### BEGIN GPL LICENSE BLOCK #####
#
#  JewelCraft jewelry design toolkit for Blender.
#  Copyright (C) 2015-2019  Mikhail Rachinskiy
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# ##### END GPL LICENSE BLOCK #####


dictionary = {
    "*": {
        "Asset Manager": "资产管理器",
        "Display Asset Name": "显示资产名称",
        "Product Report": "产品报告",
        "Report Language": "报告语言",
        "Save To File": "保存到文件",
        "Use Custom Library Folder": "使用自定义库文件夹",
        "Gems": "宝石",
        "Assets": "资源库",
        "Select Gems By...": "选择宝石...",
        "Jeweling": "珠宝",
        "Weighting": "重量评估",
        "Weighting Set": "材料设定",
        "Hide Default Sets": "隐藏默认设置",
        # "[JewelCraft] Precious": "",
        # "[JewelCraft] Precious RU (ГОСТ 30649-99)": "",
        "[JewelCraft] Base": "[JewelCraft] 基础",
        "Prongs": "起钉",
        "Cutter": "开孔器",
        "Library Folder Path": "库文件夹的路径",
        "Widgets": "检测石距小工具",
        "Use Overrides": "使用自定义覆盖",
        "Widget Color": "选择颜色",
        "Line Width": "线宽度",
        "Show Composition": "显示结构",
        "Show Density": "显示密度",
        "Composition": "结构",
        "Warnings": "警告",
        "Hidden Gems": "隐藏的宝石",
        "Show All": "显示全部",
        "Scene scale is not optimal": "场景比例不是最佳的",
        "Unsupported unit system": "不支持的单位制",
        "Overlapping Gems": "重叠宝石",
        "Limit By Selection": "按选择限制",
        "Save To Image": "保存到图像",
        "Gem Map": "宝石地图",
        "Gem Table": "宝石表",
        "Gem Size": "宝石大小",
        "Viewport Text Size": "视窗文字大小",
        "Weight": "重量",
        "Asset Name": "资产名称",
        "Category Name": "类别名称",
        "Set Name": "设置名称",
        "Curvature Scale": "弯曲比例",
        "Prong Number": "钉子数量",
        "Detalization": "详细说明",
        "Intersection": "交叉点",
        "Bump Scale": "凹凸比例",
        "Diameter": "直径",
        "Size Offset": "偏移大小",
        "Girdle": "围绕",
        "Hole": "开孔",
        "Culet": "宝石底面",
        "Handle": "处理",
        "Curve Seat": "曲线位置",
        "Curve Profile": "曲线轮廓",
        "Bevel Corners": "斜角",
        "Length Offset": "偏移长度",
        "Width Offset": "偏移宽度",
        "Position Offset": "偏移位置",
        "Start Up": "开始",
        "Mirror Axis": "对称轴",
        "Select Children": "选择子级",
        "Parent to selected": "选择父级",
        "Use 3D Cursor": "使用三维光标",
        "Collection Name": "集合名称",
        "Ring Size": "戒指尺寸",
        "USA": "美国",
        "Britain": "英国",
        "Swiss": "瑞士",
        "Japan": "日本",
        "Circumference": "周长",
        "Scatter (%)": "散开",
        "Add gemstone to the scene": "向场景添加宝石",
        "Edit selected gems": "编辑选中的宝石",
        "Commonly used precious alloys, physical properties taken directly from suppliers": "常用的贵重合金,直接从供应商处获取的物理特性",
        "Set of precious alloys according to Russian regulations": "根据俄罗斯法规的一套贵重合金",
        "Set of base metal alloys, physical properties taken directly from suppliers": "一套常见的金属合金,直接从供应商处获取的物理特性",
        "Save product report to file in project folder": "将产品报告保存到项目文件夹中的文件",
        "Product report language": "产品报告语言",
        "Use user preferences language setting": "使用语言用户首选项设置",
        "Select gems by trait": "按特征选择宝石",
        "Search stone by name": "按名称搜索石头",
        "Search asset by name": "按名称搜索资产",
        "Scatter selected object along active curve": "沿活动曲线散射选定对象",
        "Redistribute selected objects along curve": "沿曲线重新分布选定对象",
        "Display weight and volume for selected mesh objects": "显示所选网格对象的权重和体积",
        "Create instance face for selected objects": "为选定对象创建实例面",
        "Create size curve": "创建大小曲线",
        "Stretch deformed objects along curve on X axis, also works in Edit Mode with selected vertices": "沿X轴上的曲线拉伸变形对象, 也可以在编辑模式下使用选定顶点",
        "Display curve length": "显示曲线长度",
        "Move deformed object over or under the curve": "在曲线上方或下方移动变形对象",
        "Mirror selected objects around one or more axes, keeping object data linked": "围绕一个或多个轴镜像选定对象，保持对象数据链接",
        "Project selected objects onto active object using Lattice": "使用晶格将选定对象投影到活动对象上",
        # "Deform active object profile with Lattice": "",
        # "Create prongs for selected gems\n(Shortcut: hold Ctrl when using the tool to avoid properties reset)": "",
        # "Create cutter for selected gems\n(Shortcut: hold Ctrl when using the tool to avoid properties reset)": "",
        "Make curve start at the top": "使曲线从顶部开始r",
        # "Density g/cm³": "",
        "Set of materials for weighting": "用于称重的材料组",
        "Create category": "创建类别",
        "Rename category": "重命名类别",
        "Refresh asset UI": "刷新资产用户界面",
        "Add selected objects to asset library": "将所选对象添加到资源库",
        "Rename asset": "重命名资产",
        "Remove asset from library": "从库中删除资产",
        "Replace current asset with selected objects": "用所选对象替换当前资产",
        "Replace asset preview image": "替换资产预览图像",
        "Import selected asset": "导入所选资产",
        "Asset category": "资产类别",
        # "Set custom asset library folder, if disabled the default library folder will be used": "",
        # "Custom library folder path": "",
        # "Display asset name in Tool Shelf": "",
        # "Enable widgets drawing": "",
        # "Use object defined widget overrides": "",
        # "Draw widgets in front of objects": "",
        # "Override widget display properties for selected objects": "",
        # "Remove widget override properties from selected objects": "",
        # "Add new material to the list": "",
        # "Display material density in the list": "",
        # "Display material composition in the list": "",
        # "Create weighting set from materials list": "",
        # "Remove weighting set": "",
        # "Rename weighting set": "",
        # "Load weighting set to the materials list by replacing existing materials": "",
        # "Append weighting set at the end of the current materials list": "",
        # "Hide default JewelCraft sets from weighting sets menu": "",
        # "Replace selected weighting set with current materials list": "",
        # "Material name": "",
        # "Material composition": "",
        # "Use one-dimensional lattice for even deformation": "",
        # "Use two-dimensional lattice for proportional deformation": "",
        # "Scale selected objects to given size": "",
        # "Move each object individually": "",
        # "Enable material for weighting and product report": "",
        # "Parent imported asset to selected objects (Shortcut: hold Alt when using the tool)": "",
        # "Select gems that are less than 0.1 mm distance from each other or overlapping": "",
        # "Display spacing widget for all visible gems": "",
        # "Set optimal unit settings for jewelry modelling": "",
        # "Enable or disable given warning": "",
        # "Compose gem table and map it to gems in the scene": "",
        # "Present summary information about the product, including gems, sizes and weight": "",
        # "Add a new measurement": "",
        # "Remove selected item": "",
        # "Remove all list items": "",
        # "Move selected item up/down in the list": "",
        # "Measured object": "",
        # "Measurement type": "",
        # "Select material": "",
        # "Make collection instances in radial order\n(Shortcut: hold Alt when using the tool to use existing collection)": "",
        # "Include or exclude given column": "",
        # "Autoload marked weighting set on File > Open/New if materials list for given blend file is empty": "",
        "WARNING": "警告",
        "Possible gem instance face leftovers": "宝石实例面的可能残留物",
        "Hidden gems": "隐藏宝石",
        # "Deprecated gem IDs (use Convert Deprecated Gem IDs from Operator Search menu)": "",
        # "Unknown gem IDs, carats are not calculated for marked gems (*)": "",
        "Curve Length": "曲线长度",
        # "Missing selected objects": "",
        "At least two objects must be selected": "至少要选择两个对象",
        "At least one gem object must be selected": "必须至少选择一个宝石对象",
        "At least one mesh object must be selected": "必须至少选择一个网格对象",
        "Active object must be a curve": "活动对象必须是一条曲线",
        "Selected objects do not have Follow Path constraint": "所选对象没有“跟随路径”约束",
        "File not found": "找不到文件",
        "Name must be specified": "必须指定名称",
        # "Collection must be specified": "",
        "Overlapping gems": "重叠宝石",
        "{} overlaps found": "发现重叠",
        "Optimal unit settings are in use": "正在使用最佳单位设置",
        "Volume": "体积",
        "Settings": "设置",
        "Gem": "宝石",
        "Cut": "切割",
        "Qty": "数量",
        "Total (ct.)": "总数",
        "Carats": "克拉",
        "Materials": "材料费",
        "Additional Notes": "附加注释",
        "Round": "圆形",
        "Oval": "椭圆形",
        "Cushion": "垫形",
        "Pear": "梨形",
        "Marquise": "马眼形",
        "Princess": "公主方形",
        "Baguette": "长方形",
        "Square": "正方形",
        # "Asscher": "",
        # "Radiant": "",
        # "Flanders": "",
        "Octagon": "八角形",
        "Heart": "心形",
        # "Trillion": "",
        # "Trilliant": "",
        "Triangle": "三角形",
        "Alexandrite": "紫翠玉",
        "Amethyst": "紫水晶",
        "Aquamarine": "海蓝宝石",
        "Citrine": "黄水晶",
        "Cubic Zirconia": "立方氧化锆",
        "Diamond": "钻石",
        "Emerald": "绿宝石",
        "Garnet": "石榴石",
        "Morganite": "摩根石",
        "Peridot": "橄榄石",
        "Quartz": "石英",
        "Ruby": "红宝石",
        "Sapphire": "蓝宝石",
        "Spinel": "尖晶石",
        "Tanzanite": "坦桑石",
        "Topaz": "托帕石",
        "Tourmaline": "碧玺",
        "Zircon": "锆石",
        # "Yellow Gold 24K": "",
        # "Yellow Gold 22K": "",
        # "Yellow Gold 18K": "",
        # "Yellow Gold 14K": "",
        # "Yellow Gold 10K": "",
        # "White Gold 18K Pd": "",
        # "White Gold 18K Ni": "",
        # "White Gold 14K Pd": "",
        # "White Gold 14K Ni": "",
        # "White Gold 10K": "",
        # "Rose Gold 18K": "",
        # "Rose Gold 14K": "",
        # "Rose Gold 10K": "",
        # "Yellow Gold 999": "",
        # "Yellow Gold 958": "",
        # "Yellow Gold 750": "",
        # "Yellow Gold 585": "",
        # "Yellow Gold 375": "",
        # "White Gold 750 Pd": "",
        # "White Gold 750 Ni": "",
        # "White Gold 585 Pd": "",
        # "White Gold 585 Ni": "",
        # "Red Gold 585": "",
        # "Red Gold 375": "",
        # "Platinum 950": "",
        # "Platinum 900": "",
        # "Palladium 950": "",
        "Silver 925": "925银",
        # "Silver Sterling": "",
        "Brass": "黄铜",
        "Bronze": "青铜",
        # "Steel Stainless": "",
        "Titanium": "钛",
        # "mm": "",
        # "mm³": "",
        # "g": "",
        # "ct.": "",
        # "pcs": "",
    },
    "JewelCraft": {
        "Cut": "切割",
        "Round": "圆形",
        "Spacing": "设置距离",
    },
    "Dative": {
        "Size": "尺寸",
        "Stone": "石头",
        "Cut": "切割",
    },
    "Operator": {
        "Add Gem": "添加宝石",
        "Curve Scatter": "曲线分配",
        "Prongs": "起钉工具",
        "Cutter": "开孔器",
        "Make Instance Face": "使用实例面",
        # "Lattice Project": "",
        # "Lattice Profile": "",
        "Size Curve": "创建曲线",
        "Stretch": "拉长",
        "Curve Length": "测量曲线长度",
        "Product Report": "产品报告",
        "Open Library Folder": "打开库文件夹",
        "Import Asset": "导入资产",
        "Rename": "重命名",
        "Replace Asset": "替换资产",
        "Replace Preview": "替换预览",
        "Create Category": "创建类别",
        "Rename Category": "重命名类别",
        "Rename Asset": "重命名资产",
        "Remove Asset": "删除资产",
        "Replace Asset Preview": "替换资产预览",
        "Override": "自定义设置",
        "Clear List": "清空列表",
        "Add New Material": "添加新材料",
        "Create Set": "创建集合",
        "Replace Set": "替换集合",
        "Remove Set": "删除集合",
        "Rename Set": "重命名集合",
        "Overlapping": "重叠部分",
        "Set Units": "设置单位",
        "Gem Map": "宝石地图",
        "Append": "追加",
        "Add New Measurement": "添加新度量值",
        "Mark Autoload": "标记自动加载",
    },
}
